#!/bin/zsh -e
# Search for packages across every known repository
# Requires tealdeer (install with cargo install tealdeer)

if [ $# -lt 1 ]; then
  echo "requires something to search for" >2
  exit
fi

for page in /var/cache/kiss-hunt/linux/*; do
  package=$(basename ${page%%.md})
  kiss search $package 2>/dev/null || continue 
  echo -n "$package:"; awk 'NR==3' $page | cut -d'>' -f2-
done | grep $1 2>/dev/null
