#!/bin/bash -e
# Search for packages across every known repository
# Requires tealdeer (install with cargo install tealdeer)

if [ $# -lt 1 ]; then
  echo "requires something to search for" >2
  exit
fi

for page in /var/cache/kiss-hunt/tldr-master/pages/linux/*; do
  echo -n "$(basename ${page%%.md}): "; awk 'NR==3' $p
done | grep $1 2>/dev/null
