#!/bin/sh -e

:> nostrip_ # keep module signatures

mkdir -p "$1/boot"

cp config .config
make olddefconfig

make

make \
  modules_install \
  INSTALL_MOD_PATH="$1/usr"

make \
  install \
  INSTALL_PATH="$1/boot"

ls -al "$1/boot"
mv "$1/boot/vmlinuz" "$1/boot/vmlinuz-$2"
mv "$1/boot/System.map" "$1/boot/System.map-$2"
test -d /boot/efi && mkdir -p "$1/boot/efi" && cp "$1/boot/vmlinuz-$2" "$1/boot/efi/"
