#!/bin/sh -e

# utility for adding repositories
addrepo() {
  installdir=$1
  #version=$2
  reposdir=$3
  name=$4
  subdirectory=$5

  repopath="$installdir/$reposdir/$name"
  mkdir -p "$installdir/$reposdir"
  cp -r . "$repopath"
  rm -f "$repopath/addrepo" "$repopath/.build.kiss"
  mkdir -p "$installdir/etc/profile.d"
  printf 'echo $KISS_PATH | grep -q %s || export KISS_PATH=$KISS_PATH:%s/%s/%s\n' "$name" "$reposdir" "$name" "$subdirectory" \
    > "$installdir/etc/profile.d/kiss_repo-$name.sh"
}
