#!/bin/bash
IFS=:
for _hook_path in ${KISS_HOOKS_PATH:-"/etc/kiss/hooks:/usr/share/kiss/hooks"}; do set +f
  for _hook in "$_hook_path/"*sh; do
    [ -e "$_hook" ] || [ -L "$_hook" ] || continue
    TYPE=${TYPE} PKG=${PKG} DEST=${DEST} . "$_hook"
  done
done
unset IFS
