#!/bin/sh
_kiss_hooks_path=${KISS_HOOKS_PATH:-'/etc/kiss/hooks:/usr/share/kiss/hooks'}
IFS=:
for _hook_path in ${_kiss_hooks_path}; do set +f
  for _hook in "$_hook_path/"*; do
    [ -e "$_hook" ] || [ -L "$_hook" ] || continue
    case ${_hook##*/} in
      $1|*.sh)
        ./"$_hook" "$1" "$2" "$3"
        ;;
    esac
  done
done
unset IFS
