#!/bin/sh -e

ls -l

ls -l ..

make \
  INCLUDEDIR=include \
  LIBDIR=lib PREFIX=/usr \
  COMPONENT_TYPE="lib-shared"

make \
  INCLUDEDIR=include \
  LIBDIR=lib \
  PREFIX=/usr \
  DESTDIR="$1" \
  install
