#!/bin/sh -e

cp config .config

make olddefconfig

make headers

# make headers_install requires rsync, we can do better
find usr/include -name \*.h -type f | while read -r file; do
    install -Dm644 "$file" "$1/$file" 
done
