#!/bin/sh -e

repos="${KISS_REPOSITORY_PATH:-/var/db/kiss/repos}"
repo="$repos/cemkeylan"
uri="https://github.com/cemkeylan/kiss-repository.git"
mkdir -p "$1/$repos"
git clone --recursive "$uri" "$1/$repo"

mkdir -p "$1/etc/profile.d"
printf "export KISS_PATH=%s/personal:\$KISS_PATH\n" "$repo" > "$1/etc/profile.d/kiss_repo-cemkeylan.sh"
