#!/bin/sh -e

export CPPFLAGS="$CPPFLAGS -I/usr/lib/glib-2.0/include -I/usr/include/glib-2.0"
export CPPFLAGS="$CPPFLAGS -I/usr/include/gdk-pixbuf-2.0"

./configure \
    --enable-image \
    --prefix=/usr

make
make DESTDIR="$1" install
