#!/bin/zsh
# Show all the new packages added to repos recently (default 1 week)

new_packages=$(echo $KISS_PATH | tr ':' '\n' | grep -v installed | xargs -I _ \
  git -C _ --no-pager \
    log \
    --oneline \
    --since="${1:-1 week ago}" \
    --regexp-ignore-case \
    --grep 'new' \
  | cut -d':' -f1 \
  | cut -d' ' -f2 \
  | tr -d ',' \
  | sort \
  | uniq \
  | tr ' ' '\n')

for package in "${=new_packages}"; do
  description=$(kiss-describe $package)
  pkg=$(kiss search $package 2>/dev/null)
  test $pkg && mainsource=$(grep -m 1 http $pkg/sources 2>/dev/null | cut -d'/' -f1-5)
  printf "%s" "$package"
  test "$description" && printf ": %s" "$description"
  test "$mainsource" && printf " ( %s )" "$mainsource"
  printf '\n'
  unset description
  unset pkg
  unset mainsource
done
