#!/bin/zsh
# Download and edit other distro's build scripts

if [ $# -lt 1 ]; then
  echo "requires something to search for" >2
  exit
fi

downloaddir=$(mktemp -d)
pushd "$downloaddir"

for branch in main testing; do
  curl --output alpine-$branch \
    --retry 3 --silent --fail --location \
    "https://github.com/alpinelinux/aports/raw/master/$branch/$1/APKBUILD"
done

for branch in packages community; do
  curl --output arch-$branch \
    --retry 3 --silent --fail --location \
    "https://raw.githubusercontent.com/archlinux/svntogit-$branch/packages/$1/trunk/PKGBUILD"
done

for branch in base core extra game live testing wayland; do
  curl --output mue-$branch \
    --retry 3 --silent --fail --location \
    "https://raw.githubusercontent.com/muevoid/mue-linux/master/$branch/$1/build"
done

curl --output arch-aur \
  --retry 3 --silent --fail --location \
  "https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=$1"

curl --output void \
  --retry 3 --silent --fail --location \
  "https://github.com/void-linux/void-packages/raw/master/srcpkgs/$1/template"

popd

mv "$downloaddir" .
$EDITOR $(basename $downloaddir)/*
