#!/bin/sh -e

patch -p1 < no-perl.patch
mkdir -p "$1/boot"

cp config .config
make olddefconfig

make

make \
  modules_install \
  INSTALL_MOD_PATH="$1/usr"

make \
  install \
  INSTALL_PATH="$1/boot"

mv "$1/boot/vmlinuz" "$1/boot/vmlinuz-$2"
mv "$1/boot/System.map" "$1/boot/System.map-$2"

if test -d /boot/efi; then
  mkdir -p "$1/boot/efi"
  cp "$1/boot/vmlinuz-$2" "$1/boot/efi/"
fi

if test /etc/grub/grub.cfg; then
  grub-mkconfig -o /etc/grub/grub.cfg
fi
