#!/bin/sh -e

export CGO_LDFLAGS="${LDFLAGS}"
export CGO_CFLAGS="${CFLAGS}"
export CGO_CPPFLAGS="${CPPFLAGS}"
export CGO_CXXFLAGS="${CXXFLAGS}"
export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"

make bin/skopeo BUILDTAGS='containers_image_ostree_stub'
make docs

make DESTDIR="$1" install

for conf in registries.conf; do
  install -m644 "$conf" -t "$1/etc/containers/"
done

install -d "$1"/usr/share/man/man5/
for manpage in *.md; do
  go-md2man -in "$manpage" -out "$1"/usr/share/man/man5/${manpage%*.md}
done
