#!/bin/sh -e

KISS_REPO=/var/db/kiss/repo
mkdir -p "$1"/$KISS_REPO
cp -r . "$1"/"$KISS_REPO"/community
mkdir -p "$1"/etc/profile.d
printf 'export KISS_PATH=$KISS_PATH:%s\n' "$KISS_REPO"/community > "$1"/etc/profile.d/kiss-repo-community.sh

