#!/bin/sh -e

REPOS=/var/db/kiss/repos
mkdir -p "$1/$REPOS"
cp -r . "$1/$REPOS/community"
mkdir -p "$1/etc/profile.d"
printf 'export KISS_PATH=$KISS_PATH:%s\n' "$REPOS/community" > "$1/etc/profile.d/kiss-repo-community.sh"
