#!/bin/zsh
# List new and updated packages

for repo in ${(s.:.)KISS_PATH}; do
  cd $repo
  git log \
    --relative $pwd \
    --name-only \
    --since="${1:-1 week ago}" \
    --diff-filter=AM \
    --pretty=format: \
    -- */version
done \
| cut -d'/' -f1 \
| sort -u
