#!/bin/sh -e
# List installed packages which aren't present in any repository

cd "$KISS_ROOT/var/db/kiss/installed"

kiss search * | while read -r pkg_path; do echo "${pkg_path##*/}"; done | uniq -u
