#!/bin/sh -e

repos="/var/db/kiss/repos"
repo="$repos/wayland"
mkdir -p "$1/$repos"
git clone --recursive https://github.com/Himmalerin/kiss-wayland.git "$1/$repo"

mkdir -p "$1/etc/profile.d"
printf 'export KISS_PATH=$KISS_PATH:%s/kiss-wayland\n' "$repo" > "$1/etc/profile.d/kiss_repo-wayland.sh"
