#!/bin/sh -e

cd Minase-ad66673f1d8777086cf768cec0793b88b22ad455

cmake \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DCMAKE_BUILD_TYPE=Release
make

make DESTDIR="$1" install
install -Dm644 -t "$1"/usr/share/doc/minase README.md
