#!/bin/env bash
# Build a package in a container

if [ "$KISS_DEBUG" = "true" ]; then
  set -x
fi

if [ $# -lt 1 ]; then
  echo "please provide at least one package to build" >&2
  exit 1
fi

tag=armaanb/kiss:builder
git_repo="https://git.sr.ht/~armaan/dockerfiles"
git_hash="c83261b0557d18f3f2ea387ad3f22042aecd8bb6"

podman image exists "$tag" \
  || podman pull "$tag" \
  || podman build --pull-never --tag $tag --file dockerfiles-"$git_hash" "$git_repo"/archive/"$git_hash".tar.gz

CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"/kiss-ci/jedahan-repo
[[ -d "$CACHE_HOME" ]] || git clone https://github.com/jedahan/kiss-repo "$CACHE_HOME"
git -C "$CACHE_HOME" pull

podman run \
  --pull=never \
  --volume "$PWD":/root/.cache/kiss/bin \
  --volume "$CACHE_HOME":/usr/repos/jedahan \
  --env KISS_PATH="/usr/repos/jedahan:/usr/repos/official/core:/usr/repos/official/extra:/usr/repos/official/testing:/usr/repos/official/xorg:/usr/repos/community/community" \
  "$tag" \
  sh -c "/usr/repos/jedahan/kiss-bin/files/kiss-bin \$(test -f \$(kiss search $1)/depends && cat \$(kiss search $1)/depends | cut -d' ' -f1 | tr '\n' ' '); kiss build $1"
