#!/usr/bin/env bash
# Build a package in a container

if [ "$KISS_DEBUG" = "true" ]; then
  set -x
fi

if [ $# -lt 1 ]; then
  echo "please provide at least one package to build" >&2
  exit 1
fi

version=2020.9-2
tag=kiss:$version
imageid=$(podman image list --quiet $tag)

# build container if it doesn't exist
if [[ -z "$imageid" ]]; then
  containerfile_uri="https://git.sr.ht/~armaan/dockerfiles/blob/32f35a1682186934a66f42163719d6958676cbca/kiss/2020.9-2/Dockerfile"
  curl --silent $containerfile_uri | podman build --pull=never --tag $tag --file -
fi

podman run --pull=never --volume "$PWD":/root/.cache/kiss/bin "$tag" kiss build "$*"
