#!/bin/bash -e

_start_=${TMPDIR:-/tmp}/kiss-hooks-build-duration

case $1 in
pre-build)
    cat /proc/uptime > $_start
    ;;
post-build)
    IFS=. read -r _end _ < /proc/uptime
    IFS=. read -r _start _ < $_start
    rm -f $_start
    (
        _s=$((_end - _start))
        _h=$((_s / 60 / 60 % 24))
        _m=$((_s / 60 % 60))

        [ "$_h" = 0 ] || _u="${_u}${_h}h "
        [ "$_m" = 0 ] || _u="${_u}${_m}m "

        echo "$2" "Build finished in ${_u:-${_s}s}"
    )
    ;;
esac
