#!/bin/sh -e
# Print package description, falling back to tldr

package_path=$(kiss search "$@" 2>/dev/null | head -n1)

if [ -f "$package_path"/description ]; then
  command cat "$package_path"/description
else
  description=$(tldr -q "$@" 2>/dev/null | head -n2 | tail -n1 | cut -d' ' -f3-)
  if [ "$description" ]; then
    echo "$description"
  else
    command grep http "$package_path"/sources
  fi
fi
