#!/bin/sh -e

# uninstall libexecinfo if found

./configure \
    --prefix=/usr \
    --with-modules \
    --without-sound \
    --without-x \
    --without-file-notification \
    --without-dbus \
    --without-gconf \
    --without-gsettings \
    --without-makeinfo \
    --with-xpm=no

mkdir -p "$1/usr/share/emacs/site-lisp"
cat << EOF > "$1/usr/share/emacs/site-lisp/site-start.el"
;; Needed unless KISS Linux gains librsvg support
(setq-default shr-blocked-images ".*\.svg$")
EOF

make
make DESTDIR="$1" install

rm -rf "$1/usr/lib/systemd"

# reinstall libexecinfo if it was installed beforehand lol
