#!/bin/sh -e

kiss list libexecinfo && printf "libexecinfo found, please uninstall before building emacs" >&2 && false

./configure \
    --prefix=/usr \
    --with-json \
    --with-modules \
    --without-dbus \
    --without-file-notification \
    --without-gconf \
    --without-gsettings \
    --without-makeinfo \
    --without-sound \
    --without-x \
    --without-xpm

mkdir -p "$1/usr/share/emacs/site-lisp"
cat << EOF > "$1/usr/share/emacs/site-lisp/site-start.el"
;; Needed unless KISS Linux gains librsvg support
(setq-default shr-blocked-images ".*\.svg$")
EOF

make
make DESTDIR="$1" install

rm -rf "$1/usr/lib/systemd"
