#!/bin/sh -e

export DESTDIR="$1"

sed -i 's|genpeimg|# genpeimg|' meson.build

meson \
  --prefix=/usr \
  -D consolekit=false \
  -D elogind=false \
  -D gtkdoc=false \
  -D introspection=false \
  -D lvfs=false \
  -D man=false \
  -D polkit=false \
  -D systemd=false \
  -D tests=false \
  -D tpm=false \
  -D plugin_dell=true \
  -D plugin_uefi=true \
  -D plugin_altos=false \
  -D plugin_amt=false \
  -D plugin_coreboot=false \
  -D plugin_dummy=false \
  -D plugin_emmc=false \
  -D plugin_modem_manager=false \
  -D plugin_nvme=false \
  -D plugin_redfish=false \
  -D plugin_synaptics=false \
  -D plugin_thunderbolt=false \
  -D libjcat:gtkdoc=false \
  -D libjcat:introspection=false \
  -D libjcat:tests=false \
  -D libjcat:man=false \
  -D gusb:tests=false \
  -D gusb:vapi=false \
  -D gusb:docs=false \
  -D gusb:introspection=false \
  . build

ninja -C build
ninja -C build install
