#!/bin/sh -e

export DESTDIR="$1"

meson \
  --prefix=/usr \
  -D plugin_tpm=false \
  -D plugin_uefi=false \
  -D systemd=false \
  -D tests=false \
  -D man=false \
  -D consolekit=false \
  -D introspection=false \
  -D libjcat:man=false \
  -D libjcat:tests=false \
  -D libjcat:introspection=false \
  -D gusb:docs=false \
  -D gusb:introspection=false \
  -D gusb:tests=false \
  -D gusb:vapi=false \
  . build

ninja -C build
ninja -C build install
