#!/bin/sh -e

patch -p1 < no-perl.patch

scripts/setlocalversion --save-scmversion
cp config .config
make olddefconfig
make kernelrelease > version

kernver="$(cat version)"
modulesdir="$1/usr/lib/modules/$kernver"

echo "Making linux-$kernver"
make

echo "Installing modules"
make modules_install INSTALL_MOD_PATH="$1/usr"

echo "Removing unused architectures"
for arch in alpha,arc,arm,arm64,c6x,csky,h8300,hexagon,ia64,m68k,microblaze,mips,nds32,nios2,openrisc,parisc,powerpc,riscv,s390,sh,sparc,um,unicore32,xtensa; do 
    rm -rf $arch
done

echo "Symlinking built modules to /usr/src/linux"
mkdir -p "$1/usr/src"
ln -sv "/usr/lib/modules/$kernver/build" "$1/usr/src/linux"

echo "Installing kernel"
make install INSTALL_PATH="$1/boot"
cp "$1/boot/vmlinuz" "$1/boot/vmlinuz-$kernver"
cp "$1/boot/System.map" "$1/boot/System.map-$kernver"
cp ".config" "$1/boot/config-$kernver"
