#!/bin/sh -e

cd basu-dae6c703028cc9448919eca40acb7303066cd7ab
meson --prefix /usr build
ninja -C build
DESTDIR="$1" ninja -C build install
install -Dm644 -t "$1"/usr/share/basu README.md LICENSE.LGPL2.1
