#!/bin/sh -e

patch -p1 < nonrecursive-string-subst.patch

mkdir -p "$1/usr/share/xml/docbook/xsl-stylesheets-$2"

cp -R VERSION assembly common eclipse epub epub3 extensions fo highlighting \
    html htmlhelp images javahelp lib manpages params profiling roundtrip \
    slides template tests tools webhelp website xhtml xhtml-1_1 xhtml5 \
"$1/usr/share/xml/docbook/xsl-stylesheets-$2"
