name: lint packages

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint_packages:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: find packages with bad lints
        id: lint-packages
        env:
          KISS_PATH: ${{ env.GITHUB_WORKSPACE }}
        run: |
          echo kiss path is $KISS_PATH
          ls $KISS_PATH
          output=$(/usr/bin/curl --silent --location \
            https://raw.githubusercontent.com/jedahan/kiss-repo/5f4fd3b67a6cf930857fb2a5fca550e84b5eaa15/kiss-lint/files/kiss-lint \
            | /usr/bin/bash 2>&1 | sed -e 's|^.*error: |::error::|' -e 's|^.*warning: |::warning::|')
          echo $output && test -z "$output"
