name: lint packages

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint_packages:
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: find packages with bad lints
        id: lint-packages
        run: |
          /usr/bin/curl --silent --location --output kiss-lint.bash \
            https://raw.githubusercontent.com/jedahan/kiss-repo/5f4fd3b67a6cf930857fb2a5fca550e84b5eaa15/kiss-lint/files/kiss-lint
          output=$(/usr/bin/bash kiss-lint.bash . 2>&1 | sed -e 's|^.*error: |::error::|' -e 's|^.*warning: |::warning::|')
          echo $output && test -z $output
