name: build binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  update_database:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: install podman
        run: sudo apt install podman -y

      - name: checkout code
        uses: actions/checkout@v2

      - name: get changed files
        uses: jitterbit/get-changed-files@v1
        id: files

      - name: build updated binaries
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ "$changed_file" =~ ".*/version" ]]; do
              kiss-ci/files/kiss-ci $(dirname "$changed_file")
            fi
          done

      - name: add to latest release
        uses: johnwbyrd/update-release@v1
        with:
          tag: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "*.tar.gz"
