name: build binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_binaries:
    runs-on: ubuntu-20.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: get changed files
        uses: jitterbit/get-changed-files@v1
        id: files

      - name: build updated binaries
        run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ "$changed_file" =~ .*/version$ ]]; then
              KISS_DEBUG=true kiss-ci/files/kiss-ci $(dirname "$changed_file")
            fi
          done

      - name: add new binaries
        uses: jedahan/upload-assets@0.2.4
        with:
          asset_paths: '["*.tar.gz"]'
