#!/bin/sh -e

cd imv-489421b9e763865881df614a3ef550b289409677
sed -ie '/prog_a2x = find_program/,$d' meson.build

meson --prefix /usr \
  -Dwindows=wayland \
  -Dfreeimage=enabled \
  -Dlibrsvg=disabled . build

ninja -C build
DESTDIR="$1" ninja -C build install
install -Dm644 -t "$1"/usr/share/doc/imv doc/*
