#!/bin/sh -e

sed -ie '/prog_a2x = find_program/,$d' meson.build

meson --prefix /usr \
  -Dwindows=wayland \
  -Dfreeimage=enabled \
  -Dtests=disabled \
  -Dlibrsvg=disabled . build

ninja -C build
DESTDIR="$1" ninja -C build install
install -Dm644 -t "$1"/usr/share/doc/imv doc/*
