#!/bin/sh -e

sed -ie '/prog_a2x = find_program/,$d' meson.build

meson --prefix /usr \
  -Dwindows=wayland \
  -Dfreeimage=enabled \
  -Dlibrsvg=disabled . build
ninja -C build
DESTDIR="$1" ninja -C build install
